# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalelectricity',
            name='UserE',
        ),
    ]
