# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_originalelectricity_usere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalelectricity',
            name='time',
            field=models.IntegerField(max_length=6, verbose_name='时间'),
        ),
    ]
